version: '3'

services:
  mirai:
    image: reprover/mirai-http:latest
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./plugins:/app/plugins
    ports: 
      - 8080:8080
      