version: '3'

services:
  mirai:
    image: llpp9980/mirai-docker-starter:latest
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./plugins:/app/plugins
      - ./bots:/app/bots
    ports: 
      - 8080:8080
      